INHERIT: ./mkdocs-alternate-langs.yml
site_name: Grist Help Center
site_dir: site
site_description: "Tutorials and resources for Grist, to help you organize your data, your way."
site_url: "https://support.getgrist.com"
repo_name: "GitHub"
repo_url: "https://github.com/gristlabs/grist-help"

# use directory urls (for prettiness) unless running htmlproofing
# (which is confused by them).
use_directory_urls: !ENV [HTMLPROOFER_OVERRIDE_USE_DIRECTORY_URLS, true]

docs_dir: './help/en/docs' # Add localization folder here for now, we'll handle i18n later
# windmill is a theme maintained by Grist Labs in https://github.com/gristlabs/mkdocs-windmill
theme:
  name: windmill
  custom_dir: overrides
  # Disable the language selector when running in live (so for a specific language)
  disable_language_selector: !ENV [DISABLE_LANGUAGE_SELECTOR, false]

extra:
  logo: 'images/logo.png'
  palette:
    primary: 'blue grey'
    accent: 'orange'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  homepage: '/help'
  version: '1.0.2-dev'
  article_nav_bottom: false
  history_buttons: false
  home_links:
    - href: https://community.getgrist.com
      text: 'Community'
    - href: https://www.getgrist.com
      text: 'Back to Grist'
      hide_on_small_screen: true
  google_tag_manager: 'GTM-5FDHKQ9'
extra_css:
  - css/grist.css
extra_javascript:
  - js/grist.js

plugins:
  - search
  - awesome-pages
  - htmlproofer:
      enabled: !ENV [HTMLPROOFER_ENABLED, false]
      validate_external_urls: false
  - meta-descriptions

markdown_extensions:
  toc:
      permalink: '#'
  admonition: {}
  smarty: {}
  extra: {}
  meta: {}
  attr_list: {}

hooks:
- ../../mkdocs-utils/hooks.py
