INHERIT: ../../mkdocs.yml
docs_dir: './docs'
theme:
  custom_dir: ../../overrides
  language: en

nav:
  - Welcome to Grist: index.md
  - FAQ: FAQ.md
  - How-to tutorials:
    - Create your own CRM: lightweight-crm.md
    - Analyze and visualize: investment-research.md
    - Manage business data: afterschool-program.md
  - Managing documents:
    - Creating a document: creating-doc.md
    - Sharing a document: sharing.md
    - Copying documents: copying-docs.md
    - Importing more data: imports.md
    - Exports & backups: exports.md
    - Automatic backups: automatic-backups.md
    - Document history: document-history.md
    - Workspaces: workspaces.md
  - Pages and tables:
    - Entering data: enter-data.md
    - Pages & widgets: page-widgets.md
    - Raw data: raw-data.md
    - Search, sort & filter: search-sort-filter.md
    - Table widget: widget-table.md
    - Card & card list: widget-card.md
    - Form: widget-form.md
    - Chart: widget-chart.md
    - Calendar: widget-calendar.md
    - Custom: widget-custom.md
    - Linking widgets: linking-widgets.md
    - Custom layouts: custom-layouts.md
    - Record cards: record-cards.md
    - Summary tables: summary-tables.md
    - On-demand tables: on-demand-tables.md
  - Columns and data types:
    - Columns & types: col-types.md
    - Reference columns: col-refs.md
    - Conditional formatting: conditional-formatting.md
    - Timestamp columns: timestamps.md
    - Authorship columns: authorship.md
    - Transformations: col-transform.md
  - Using formulas:
    - Intro to formulas: formulas.md
    - References and lookups: references-lookups.md
    - Working with dates: dates.md
    - Formula timer: formula-timer.md
    - Python versions: python.md
    - Function reference: functions.md
    - Formula cheat sheet: formula-cheat-sheet.md
  - AI Formula Assistant:
    - AI Formula Assistant: ai-assistant.md
  - Team sites:
    - Creating team sites: teams.md
    - Sharing team sites: team-sharing.md
  - Access rules:
    - Intro to access rules: access-rules.md
  - Integrations:
    - REST API usage: rest-api.md
    - REST API reference: api.md
    - Integrator services: integrators.md
    - Embedding: embedding.md
    - Webhooks: webhooks.md
    - Plugin API:
      - Intro to Plugin API: code/README.md
      - grist-plugin-api: code/modules/grist_plugin_api.md
      - ... | flat | **/code/interfaces/**
      - ... | flat | **/code/modules/**
  - Self-managed:
    - Self-managed Grist: self-managed.md
    - SAML: install/saml.md
    - OIDC: install/oidc.md
    - Forwarded headers: install/forwarded-headers.md
    - Cloud storage: install/cloud-storage.md
    - GristConnect: install/grist-connect.md
    - AWS Marketplace: install/aws-marketplace.md
    - Telemetry:
      - Overview of telemetry: telemetry.md
      - Limited telemetry: telemetry-limited.md
      - Full telemetry: telemetry-full.md
  - News & updates:
    - Newsletters: newsletters.md
    - 2024/07: newsletters/2024-07.md
    - 2024/06: newsletters/2024-06.md  
    - 2024/05: newsletters/2024-05.md  
    - 2024/04: newsletters/2024-04.md      
    - 2024/03: newsletters/2024-03.md    
    - 2024/02: newsletters/2024-02.md
    - 2024/01: newsletters/2024-01.md
    - 2023/12: newsletters/2023-12.md
    - 2023/11: newsletters/2023-11.md
    - 2023/10: newsletters/2023-10.md
    - 2023/09: newsletters/2023-09.md
    - 2023/08: newsletters/2023-08.md
    - 2023/07: newsletters/2023-07.md
    - 2023/06: newsletters/2023-06.md
    - 2023/05: newsletters/2023-05.md
    - 2023/04: newsletters/2023-04.md
    - 2023/03: newsletters/2023-03.md
    - 2023/02: newsletters/2023-02.md
    - 2023/01: newsletters/2023-01.md
    - 2022/12: newsletters/2022-12.md
    - 2022/11: newsletters/2022-11.md
    - 2022/10: newsletters/2022-10.md
    - 2022/09: newsletters/2022-09.md
    - 2022/08: newsletters/2022-08.md
    - 2022/07: newsletters/2022-07.md
    - 2022/06: newsletters/2022-06.md
    - 2022/05: newsletters/2022-05.md
    - 2022/04: newsletters/2022-04.md
    - 2022/03: newsletters/2022-03.md
    - 2022/02: newsletters/2022-02.md
    - 2022/01: newsletters/2022-01.md
    - 2021/12: newsletters/2021-12.md
    - 2021/11: newsletters/2021-11.md
    - 2021/10: newsletters/2021-10.md
    - 2021/09: newsletters/2021-09.md
    - 2021/08: newsletters/2021-08.md
    - 2021/07: newsletters/2021-07.md
    - 2021/06: newsletters/2021-06.md
    - 2021/05: newsletters/2021-05.md
    - 2021/04: newsletters/2021-04.md
    - 2021/03: newsletters/2021-03.md
    - 2021/02: newsletters/2021-02.md
    - 2021/01: newsletters/2021-01.md
    - 2020/12: newsletters/2020-12.md
    - 2020/11: newsletters/2020-11.md
    - 2020/10: newsletters/2020-10.md
    - 2020/09: newsletters/2020-09.md
    - 2020/08: newsletters/2020-08.md
    - 2020/07: newsletters/2020-07.md
    - 2020/06: newsletters/2020-06.md
    - 2020/05: newsletters/2020-05.md
  - More examples:
      - More examples: examples.md
      - Credit card expenses: examples/2020-06-credit-card.md
      - Book club links: examples/2020-06-book-club.md
      - Prefill emails: examples/2020-07-email-compose.md
      - Prepare invoices: examples/2020-08-invoices.md
      - Track payroll: examples/2020-09-payroll.md
      - Print mailing labels: examples/2020-10-print-labels.md
      - Treasure hunt: examples/2020-11-treasure-hunt.md
      - Map: examples/2020-12-map.md
      - Task management: examples/2021-01-tasks.md
      - Lead list: examples/2021-03-leads.md
      - Link keys guide: examples/2021-04-link-keys.md
      - Reference columns guide: examples/2021-05-reference-columns.md
      - Summary tables guide: examples/2021-06-timesheets.md
      - Time and user stamps: examples/2021-07-auto-stamps.md
      - Restrict duplicate records: examples/2023-01-acl-memo.md
      - Proposals & contracts: examples/2023-07-proposals-contracts.md
  - Reference:
    - Keyboard shortcuts: keyboard-shortcuts.md
    # The function reference (functions.md) is listed above; here is an intentionally non-standard
    # link, so that only the above page item gets highlighted when the function reference is open.
    - Function reference: /functions/
    - Limits: limits.md
    - Data security: data-security.md
    - Browser support: browser-support.md
    - Glossary: glossary.md

