name: Publish Live
on:
  push:
    branches:
      - master
jobs:
  publish-live:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Fetch origin/gh-pages
        run: git fetch origin gh-pages

      - name: Building the documentation
        run: python3 ./docs.py build-all

      - name: Publish live
        run: |
          ghp-import -m "Deployed ${GITHUB_SHA:0:7} with MkDocs version: $(pip show mkdocs | grep -Po "Version: \K.*")" -p site
